name: localsend
title: Localsend
version: 1.15.3
license: MIT
website: https://localsend.org/
source-code: https://github.com/localsend/localsend
issues: https://github.com/localsend/snap
type: app
icon: snap/gui/localsend.png
summary: Share files to nearby devices
description: |
  This app allows you to send files and messages over the local LAN network.

  In contrast to most alternatives, no external servers are needed. Everything happens locally in the wifi network.

confinement: strict
base: core24
compression: lzo
grade: stable
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

parts:
  localsend:
    plugin: dump
    source:
      - on amd64: https://github.com/localsend/localsend/releases/download/v$SNAPCRAFT_PROJECT_VERSION/LocalSend-$SNAPCRAFT_PROJECT_VERSION-linux-x86-64.deb
      - on arm64: https://github.com/localsend/localsend/releases/download/v$SNAPCRAFT_PROJECT_VERSION/LocalSend-$SNAPCRAFT_PROJECT_VERSION-linux-arm-64.deb

apps:
  localsend:
    command: usr/share/localsend_app/localsend_app
    extensions: [gnome]
    plugs:
      - home
      - removable-media # no auto-connect
      - network
      - network-manager # no auto-connect, enabling fixes AppArmor denials in log
