name: localsend-uno
title: Localsend (unofficial)
version: 1.14.0
license: MIT
website: https://localsend.org/
source-code: https://github.com/localsend/localsend
issues: https://github.com/thatLeaflet/localsend-snap/issues
type: app
icon: snap/gui/localsend.png
summary: Share files to nearby devices
description: |
  This app allows you to send files and messages over the local LAN network.

  In contrast to most alternatives, no external servers are needed. Everything happens locally in the wifi network.
  
  Note: This is an unofficial repackaging and is not endorsed by the upstream project. Additionally, after the install, you must run: `snap connect localsend-uno:network-manager`

confinement: strict
base: core22
compression: lzo
grade: stable
architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [amd64]
    build-for: [arm64]

parts:
  localsend:
    plugin: dump
    source:
      - on amd64: https://github.com/localsend/localsend/releases/download/v$SNAPCRAFT_PROJECT_VERSION/LocalSend-$SNAPCRAFT_PROJECT_VERSION-linux-x86-64.deb
      - on arm64: https://github.com/localsend/localsend/releases/download/v$SNAPCRAFT_PROJECT_VERSION/LocalSend-$SNAPCRAFT_PROJECT_VERSION-linux-arm-64.deb

apps:
  localsend-uno:
    command: usr/share/localsend_app/localsend_app
    extensions: [gnome]
    plugs:
      - home
      - removable-media # no auto-connect
      - network
      - network-manager # no auto-connect, enabling fixes AppArmor denials in log
